### ISSUE TITLE
Feature Request : Sync without having to close/reopen

### ISSUE THREAD

**Issue by brennanyoung** [mohzy83/NppMarkdownPanel#15] opened 2019-08-22 12:04 UTC
I'd like the viewer panel to display my latest .md changes. The only way I can see to do this is to **close** and **reopen** the panel. 

That's two clicks on a tiny, tiny button which require me to take my hands off the keyboard.

If we can't have the markdown in sync with individual keystrokes (perhaps some milliseconds after the last keystroke), could we instead have some kind of UI for 'sync'? 

Perhaps a button?
Perhaps a menu item with a shortcut?
Perhaps just sync the view when you save?

It should happen quickly, easily, and (preferably) without taking the hands off the keyboard because the use case of markdown is people using a keyboard who are too busy to faff around with closing tags, so they're certainly too busy to take their hands off the keyboard.

**Comment by andrzejQ** [comment] 2019-10-18 11:49
For now, before the solution appears, you may want to assign a hotkey, such as [Ctrl+Shift+M] in:

Macro \ Modify Shortcut \ Plugin Commands

Then you can press [Ctrl+Shift+M+M] (twice M).
![ShortcutMapper](https://user-images.githubusercontent.com/36765728/67091858-0c088800-f1ae-11e9-98d7-042e0858d4ed.png)

**Comment by andrzejQ** [comment] 2019-10-21 11:30
In N++ v.7.8 you can press [Ctrl+R].

**Comment by mohzy83** [comment] 2020-10-16 10:12
By default the panel updates itself after a short delay to reflect all changes in the .md-file.
See how it works for me.
![npOigSI9ID](https://user-images.githubusercontent.com/26003088/96246203-9a257300-0fa8-11eb-9e55-c6351752e526.gif)
This is not working for you?

**Comment by ant1j** [comment] 2020-12-04 04:13
I have the same issue: the MD preview panel is not updating as I type & update the text.

**Comment by cyberdyne101** [comment] 2020-12-04 09:44
I'm suffering from this bug, (using x64) and if it is because what I think it is, it will not affect x32. Please see below.
This is probably related to the issue is filed for MarkDownViewer++ but if you read the thread you can see it also relates to NppMarkdownPanel:
https://github.com/nea/MarkdownViewerPlusPlus/issues/107

And the real, underlying issue seems to be because of this:
https://community.notepad-plus-plus.org/topic/17755/notepad-7-7-breaking-change-of-scnotification-definition-in-x64-build

**Comment by PawelWozniak** [comment] 2021-01-25 11:26
This is still an issue. I am using 7.9.2 x64 and Markdown Panel plugin.
View is not refreshed.

**Comment by mohzy83** [comment] 2022-05-26 19:44
fixed in version 0.6.1

**Closed by mohzy83** 2022-05-26 19:44 UTC
Labels: bug
